export const FETCH_MSGS_HEADERS = 'FETCH_MSGS_HEADERS'
export const FETCH_MSG = 'FETCH_MSG'
export const FETCH_TOKEN_HOLDERS = 'FETCH_TOKEN_HOLDERS'

export const ACTION_TYPES = {
  [FETCH_MSGS_HEADERS]: FETCH_MSGS_HEADERS,
  [FETCH_MSG]: FETCH_MSG,
  [FETCH_TOKEN_HOLDERS]: FETCH_TOKEN_HOLDERS,
}
