// app state
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'
export const SET_LOCK_STATE = 'SET_LOCK_STATE'
export const SET_INBOX_CONTRACT_ADDR = 'SET_INBOX_CONTRACT_ADDR'
export const SET_INBOX_CONTRACT_OBJ = 'SET_INBOX_CONTRACT_OBJ'
export const SET_WEB3_ADDR = 'SET_WEB3_ADDR'
// search
export const SET_SEARCH_TOKENS_ADDR = 'SET_SEARCH_TOKENS_ADDR'
export const SET_SEARCH_MSGS_ADDR = 'SET_SEARCH_MSGS_ADDR'
// messages
export const SET_MSGS = 'SET_MSGS'
export const SET_MSGS_HEADERS = 'SET_MSGS_HEADERS'
// token holders
export const SET_TOKEN_HOLDERS = 'SET_TOKEN_HOLDERS'

export const MUTATION_TYPES = {
  // app state
  [ADD_NOTIFICATION]: ADD_NOTIFICATION,
  [REMOVE_NOTIFICATION]: REMOVE_NOTIFICATION,
  [SET_LOCK_STATE]: SET_LOCK_STATE,
  [SET_INBOX_CONTRACT_ADDR]: SET_INBOX_CONTRACT_ADDR,
  [SET_INBOX_CONTRACT_OBJ]: SET_INBOX_CONTRACT_OBJ,
  [SET_WEB3_ADDR]: SET_WEB3_ADDR,
  // search
  [SET_SEARCH_MSGS_ADDR]: SET_SEARCH_MSGS_ADDR,
  [SET_SEARCH_TOKENS_ADDR]: SET_SEARCH_TOKENS_ADDR,
  // messages
  [SET_MSGS]: SET_MSGS,
  [SET_MSGS_HEADERS]: SET_MSGS_HEADERS,
  // token holders
  [SET_TOKEN_HOLDERS]: SET_TOKEN_HOLDERS,
}
