export const ADD_ADDR = 'ADD_ADDR'
export const REMOVE_ADDR = 'REMOVE_ADDR'

export const SET_MESSAGES_FOR_ADDR = 'SET_MESSAGES_FOR_ADDR'
export const SET_CURRENT_MESSAGE_ID = 'SET_CURRENT_MESSAGE_ID'

export const SET_EIP_FOR_ADDR = 'SET_EIP_FOR_ADDR'

export const MUTATION_TYPES = {
  [ADD_ADDR]: ADD_ADDR,
  [REMOVE_ADDR]: REMOVE_ADDR,

  [SET_MESSAGES_FOR_ADDR]: SET_MESSAGES_FOR_ADDR,
  [SET_CURRENT_MESSAGE_ID]: SET_CURRENT_MESSAGE_ID,

  [SET_EIP_FOR_ADDR]: SET_EIP_FOR_ADDR,
}
