// App State
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'

export const UPDATE_WEB3_PROVIDER = 'UPDATE_WEB3_PROVIDER'
export const RESET_WEB3_PROVIDER = 'RESET_WEB3_PROVIDER'

export const UPDATE_INBOX_ACCT_ID = 'UPDATE_INBOX_ACCT_ID'
export const RESET_INBOX_ACCT_ID = 'RESET_INBOX_ACCT_ID'

export const UPDATE_INBOX_CONTRACT_ID = 'UPDATE_INBOX_CONTRACT_ID'
export const RESET_INBOX_CONTRACT_ID = 'RESET_INBOX_CONTRACT_ID'

export const UPDATE_INBOX_CONTRACT_OBJ = 'UPDATE_INBOX_CONTRACT_OBJ'
export const RESET_INBOX_CONTRACT_OBJ = 'RESET_INBOX_CONTRACT_OBJ'

export const UPDATE_WEB3_ACCT_ID = 'UPDATE_WEB3_ACCT_ID'
export const RESET_WEB3_ACCT_ID = 'RESET_WEB3_ACCT_ID'

export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'
export const RESET_MESSAGES = 'RESET_MESSAGES'

export const MUTATION_TYPES = {
  // App State
  [UPDATE_NOTIFICATIONS]: UPDATE_NOTIFICATIONS,
  [REMOVE_NOTIFICATION]: REMOVE_NOTIFICATION,

  [UPDATE_WEB3_PROVIDER]: UPDATE_WEB3_PROVIDER,
  [RESET_WEB3_PROVIDER]: RESET_WEB3_PROVIDER,

  [UPDATE_INBOX_ACCT_ID]: UPDATE_INBOX_ACCT_ID,
  [RESET_INBOX_ACCT_ID]: RESET_INBOX_ACCT_ID,

  [UPDATE_INBOX_CONTRACT_ID]: UPDATE_INBOX_CONTRACT_ID,
  [RESET_INBOX_CONTRACT_ID]: RESET_INBOX_CONTRACT_ID,

  [UPDATE_INBOX_CONTRACT_OBJ]: UPDATE_INBOX_CONTRACT_OBJ,
  [RESET_INBOX_CONTRACT_OBJ]: RESET_INBOX_CONTRACT_OBJ,

  [UPDATE_WEB3_ACCT_ID]: UPDATE_WEB3_ACCT_ID,
  [RESET_WEB3_ACCT_ID]: RESET_WEB3_ACCT_ID,

  [UPDATE_MESSAGES]: UPDATE_MESSAGES,
  [RESET_MESSAGES]: RESET_MESSAGES,
}
