const MESSAGES_PAGE = 'MESSAGES_PAGE'
const TOKENS_PAGE = 'TOKENS_PAGE'
const COMPOSE_PAGE = 'COMPOSE_PAGE'

export default {
  [MESSAGES_PAGE]: MESSAGES_PAGE,
  [TOKENS_PAGE]: TOKENS_PAGE,
  [COMPOSE_PAGE]: COMPOSE_PAGE,
}
